ai:
    platform:
        ollama:
            endpoint: '%env(OLLAMA_HOST_URL)%'

    agent:
        default:
            model: '%env(OLLAMA_CHAT_MODEL)%'
            prompt:
                file: '%kernel.project_dir%/prompts/default.txt'
                include_tools: true

    message_store:
        session:
            default:
                identifier: 'chat'

    chat:
        default:
            agent: 'ai.agent.default'
            message_store: 'ai.message_store.session.default'
