twig:
    file_name_pattern: '*.twig'
    globals:
        umami_script_url: '%env(string:default::UMAMI_SCRIPT_URL)%'
        umami_website_id: '%env(string:default::UMAMI_WEBSITE_ID)%'

when@test:
    twig:
        strict_variables: true
